"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
from pathlib import Path
from datetime import timedelta
import os
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# 1. Load the environment variables from the .env file
# This must be called before trying to access the variables.
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ['*']


AUTH_USER_MODEL = 'base.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",
    'base.apps.BaseConfig',
    'rest_framework',
    'corsheaders',
    "cloudinary",
    "cloudinary_storage",
    "rest_framework_simplejwt.token_blacklist",
    'rest_framework.authtoken',
    "django_rest_passwordreset",
    "dj_rest_auth",
]

DJANGO_REST_MULTITOKENAUTH_REQUIRE_USABLE_PASSWORD = False
DJANGO_REST_PASSWORDRESET_REQUIRE_USABLE_PASSWORD = False

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
'default': dj_database_url.config(
    engine='django.db.backends.postgresql',
    default=os.environ.get('DATABASE_URL'),
    )
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # Global default, strictly override in views
    ),
}

SIMPLE_JWT = {
    # Token life span
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=50),  # Short life for security
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Longer life for convenience

    # Other useful settings
    'ROTATE_REFRESH_TOKENS': True, # Rotates the refresh token on every refresh
    'BLACKLIST_AFTER_ROTATION': True, # Blacklist the old refresh token
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}


# Add our custom X-Device-ID to the list of allowed headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-device-id",
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


###### Payment Integration ######
PAYPAL_CLIENT_ID = os.environ.get('sand_box_paypal_client_id')
PAYPAL_SECRET = os.environ.get('sand_box_paypal_secret')
PAYPAL_API_URL = os.environ.get('sand_box_PAYPAL_API_URL') # sand_box version


# settings.py
STRIPE_SECRET_KEY = os.environ.get('stripe_secret_key')
# This is for you (backend)
STRIPE_PUBLISHABLE_KEY = os.environ.get('stripe_publishable_key')
# You will give this to the frontend team
STRIPE_WEBHOOK_SECRET = os.environ.get('stripe_webhook_secret', default='')

PAYMOB_API_KEY = os.environ.get('PAYMOB_API_KEY')
PAYMOB_INTEGRATION_ID = os.environ.get('PAYMOB_INTEGRATION_ID')
PAYMOB_WALLET_INTEGRATION_ID = os.environ.get('PAYMOB_WALLET_INTEGRATION_ID')
PAYMOB_HMAC_SECRET = os.environ.get('PAYMOB_HMAC_SECRET')
PAYMOB_IFRAME_ID = os.environ.get('PAYMOB_IFRAME_ID')

# Webhook secret for verifying Stripe webhook events
DOMAIN_URL = os.environ.get('domain_url')
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## Google Login Shit
SITE_ID = 1



## EMAIL SHIT
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
