# Generated by Django 5.2.4 on 2025-12-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
