# Generated by Django 5.2.9 on 2026-02-16 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cartitem_options_productvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('device_id__isnull', False), _connector='OR'), name='cart_must_have_customer_or_device'),
        ),
    ]
