# Generated by Django 5.2.9 on 2026-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material_composition',
        ),

        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fragrance_family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='volume',
            field=models.CharField(default='100ml', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'volume')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
    ]
