# Generated by Django 5.2.9 on 2026-04-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_banner_mobile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='desktop_image',
        ),
    ]
